In [1]:
from __future__ import print_function
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets
import numpy as np
import matplotlib.pylab as plt
import matplotlib
# matplotlib.use('Qt4Agg')
from numpy import linalg as la
from scipy.optimize import fsolve
from scipy import linalg as scpla
import seaborn as sb

# dissect Jt matrix to rank-1 and rank-1
J,dJ = np.zeros((2,2)),np.zeros((2,2))
JE,JI,a,b=0.6,0.8,0.2,0.4
J[:,0],J[:,1]=JE,-JI
dJ[0,0],dJ[1,0]=-a,a
dJ[0,1],dJ[1,1]=b,-b
Jt=J+dJ
# m and n
m,n=np.array([[1,1],[1,-1]]),np.array([[JE,-a],[-JI,b]])
m1,m2=np.reshape(m[:,0],(2,1)),np.reshape(m[:,1],(2,1))
n1,n2=np.reshape(n[:,0],(2,1)),np.reshape(n[:,1],(2,1))
print('recon:',m@n.T)

overlap=n.T@m
eigv,eigvec=la.eig(Jt)
eigv_,eigvec_=la.eig(overlap)
print('original:',eigv)
print('overlap:',eigv_)
print('cos org:',eigvec[:,0].T@eigvec[:,1])
print('cos trans:',eigvec_[:,0].T,eigvec_[:,1])
eigvec1,eigvec2=n.T@eigvec[:,0],n.T@eigvec[:,1]
eigvec1_=eigvec1*np.sqrt(2)/eigv[0]
eigvec1/=np.sqrt(np.sum(eigvec1**2))
eigvec2/=np.sqrt(np.sum(eigvec2**2))
print('vec trans:',eigvec1_,eigvec1)
print('theo trans:',eigvec1.T@eigvec2)
print('theo trans(t):',eigvec[:,0].T@eigvec[:,1])

recon: [[ 0.4 -0.4]
 [ 0.8 -1.2]]
original: [ 0.16568542 -0.96568542]
overlap: [ 0.16568542 -0.96568542]
cos org: 0.7276068751089988
cos trans: [0.96753822 0.25272473] [-0.8773552   0.47984149]
vec trans: [0.96753822 0.25272473] [0.96753822 0.25272473]
theo trans: -0.7276068751089988
theo trans(t): 0.7276068751089988


In [2]:
# dissect Jt matrix to rank-1 and rank-1
J,dJ = np.zeros((2,2)),np.zeros((2,2))
JE,JI,a,b=0.6,0.8,0.2,0.4
J[:,0],J[:,1]=JE,-JI
dJ[0,0],dJ[1,0]=-a,a
dJ[0,1],dJ[1,1]=b,-b
Jt=J+dJ
# m and n
lv,sigv,nh=la.svd(Jt)
n=nh.T
m=lv.copy()
m[:,0]*=sigv[0]
m[:,1]*=sigv[1]

# m,n=np.array([[1,1],[1,-1]]),np.array([[JE,-a],[-JI,b]])
# m1,m2=np.reshape(m[:,0],(2,1)),np.reshape(m[:,1],(2,1))
# n1,n2=np.reshape(n[:,0],(2,1)),np.reshape(n[:,1],(2,1))
print('recon:',m@n.T)

overlap=n.T@m
eigv,eigvec=la.eig(Jt)
eigv_,eigvec_=la.eig(overlap)
print('original:',eigv)
print('overlap:',eigv_)
print('cos org:',eigvec[:,0].T@eigvec[:,1])
print('cos trans:',eigvec_[:,0].T@eigvec_[:,1])
eigvec1,eigvec2=n.T@eigvec[:,0],n.T@eigvec[:,1]
print('vec trans:',eigvec_)
print('theo trans:',eigvec1.T,eigvec2)
print('theo trans(t):',eigvec2.T@eigvec1)
print(n.T@n)

recon: [[ 0.4 -0.4]
 [ 0.8 -1.2]]
original: [ 0.16568542 -0.96568542]
overlap: [-0.96568542  0.16568542]
cos org: 0.7276068751089988
cos trans: -0.7276068751089987
vec trans: [[-0.62254144 -0.08388471]
 [ 0.78258684 -0.99647547]]
theo trans: [-0.08388471 -0.99647547] [ 0.62254144 -0.78258684]
theo trans(t): 0.7276068751089989
[[ 1.00000000e+00 -9.58829555e-18]
 [-9.58829555e-18  1.00000000e+00]]


In [3]:
fakeeigvec=eigvec#np.random.random((2,2))
print(fakeeigvec)
fakeeigvec[:,0]/=np.sqrt(np.sum(fakeeigvec[:,0]**2))
fakeeigvec[:,1]/=np.sqrt(np.sum(fakeeigvec[:,1]**2))
feigvec1,feigvec2=n.T@eigvec[:,0],n.T@eigvec[:,1]
print(feigvec1,feigvec2)
print(np.sum(fakeeigvec[:,0]**2),';',np.sum(fakeeigvec[:,1]**2))
feigvec1/=np.sqrt(np.sum(feigvec1**2))
feigvec2/=np.sqrt(np.sum(feigvec2**2))
print('cos 0:',np.sum(feigvec1*feigvec2))
print('cos 1:',fakeeigvec[:,0].T@fakeeigvec[:,1])


[[0.86285621 0.28108464]
 [0.50544947 0.95968298]]
[-0.08388471 -0.99647547] [ 0.62254144 -0.78258684]
1.0 ; 1.0
cos 0: 0.7276068751089991
cos 1: 0.7276068751089989


In [4]:
# dissect Jt matrix to rank-1 and rank-1
J,dJ = np.zeros((2,2)),np.zeros((2,2))
JE,JI,a,b=1.6,0.8,0.030,0.020#0.01,0.02
# # 1-JE+JI+a+b+2*(a*JI-b*JE)=0
# b = (1-JE+JI+a*(1+2*JI))/(2*JE-1)
# if aJE+bJI=0
b=-a*JE/JI
print('b,cal:',b)
J[:,0],J[:,1]=JE,-JI
dJ[0,0],dJ[1,0]=-a,a
dJ[0,1],dJ[1,1]=b,-b
Jt=J+dJ
# m and n
m,n=np.array([[1,1],[1,-1]]),np.array([[JE,-a],[-JI,b]])
m1,m2=np.reshape(m[:,0],(2,1)),np.reshape(m[:,1],(2,1))
n1,n2=np.reshape(n[:,0],(2,1)),np.reshape(n[:,1],(2,1))
Jo = n.T@m
eigvo,eigveco=la.eig(Jo)
# print('eigenvalue of Jo:',eigvo)
# real SVD
lvec,sigv,rvech=la.svd(Jt)
sigmav=np.zeros((2,2),dtype=complex)
sigmavinv= np.zeros((2,2),dtype=complex)
for i in range(2):
    sigmav[i,i]=sigv[i]
    sigmavinv[i,i]=1/sigv[i]
rvec=rvech.T
mlvec=lvec.copy()

mlvec[:,0],mlvec[:,1]=mlvec[:,0]*sigv[0],mlvec[:,1]*sigv[1]
# print('M check',mlvec@np.array([[1/sigv[0],0],[0,1/sigv[1]]])*-np.sqrt(2),' or:',m)
rotm=mlvec@np.array([[1/sigv[0],0],[0,1/sigv[1]]])*np.sqrt(2)
invm=la.inv(m)
Mcheck=invm@rotm
print('rotation',Mcheck,' inv:',la.inv(Mcheck),' trans:',Mcheck.T)
genover,svdover=n.T@m,rvech@mlvec
# mrecon=np.sqrt(2)*mlvec@(sigmavinv)@Mcheck.T
# print('M:',m,' or con:',mrecon)
# nrecon=Mcheck@sigmav@rvech/np.sqrt(2)
# print('N:',n,' or con:',nrecon)
geneigv,geneigvec=la.eig(genover)
svdeigv,svdeigvec=la.eig(svdover)
print('eigenvalue generalized overlap:',geneigv,'; svd overlap:',svdeigv)
traneigv=sigmavinv@Mcheck.T@geneigvec[:,0]
print(traneigv,' or',svdeigvec[:,0])
NMover=Mcheck@sigmav@rvech@mlvec@sigmavinv@Mcheck.T
print('NMCON:',NMover,' or ',genover)
newvec=rvech@mlvec@sigmavinv@Mcheck.T@geneigvec[:,0]
print('new lhs',newvec)
newvecr=sigmavinv@Mcheck.T@geneigvec[:,0]#geneigv[0]*
print('new rhs',newvecr)
print('eigenvector nm:',newvecr/svdeigvec[:,0])
S,Sp,Delta,Deltap=JE+JI,a+b,JE-JI,a-b
lambda_o=(Delta-Sp-np.sqrt((Delta+Sp)**2-4*Deltap*S))/2.0
print(la.eig(genover),lambda_o)
print('u1/u2',geneigvec[0,0]/geneigvec[1,0],'; appro:',-(Delta+Sp)/Deltap)
print('u1/u2',geneigvec[0,1]/geneigvec[1,1],'; appro:',-S/(Delta+Sp))



b,cal: -0.06
rotation [[-1.00000000e+00  0.00000000e+00]
 [-1.11022302e-16 -1.00000000e+00]]  inv: [[-1.00000000e+00 -0.00000000e+00]
 [ 1.11022302e-16 -1.00000000e+00]]  trans: [[-1.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00 -1.00000000e+00]]
eigenvalue generalized overlap: [0.415+0.26033632j 0.415-0.26033632j] ; svd overlap: [0.415+0.26033632j 0.415-0.26033632j]
[-0.38807526-4.67358033e-18j  1.66009974-1.12255651e+00j]  or [-0.15749089-0.10649506j  0.98176139+0.j        ]
NMCON: [[ 0.8 +0.j  2.4 +0.j]
 [-0.09+0.j  0.03+0.j]]  or  [[ 0.8   2.4 ]
 [-0.09  0.03]]
new lhs [-0.16105123-0.10103009j  0.98118362-0.0336767j ]
new rhs [-0.38807526-4.67358033e-18j  1.66009974-1.12255651e+00j]
eigenvector nm: [1.69094014-1.14341074j 1.69094014-1.14341074j]
(array([0.415+0.26033632j, 0.415-0.26033632j]), array([[ 0.98176139+0.j        ,  0.98176139-0.j        ],
       [-0.15749089+0.10649506j, -0.15749089-0.10649506j]])) nan
u1/u2 (-4.277777777777777-2.892625788209959j) ; appro: -8.55555555

In [5]:
# We can figure out how the dynamics of kappa under different basis vectors
# let the derivative of the transfer function equals to the eigenvalue of the overlap matrix
# the identical eigenvalues for overlap matrix nTm and NTM
eigv,eigvec=la.eig(rvech@mlvec)
eigv_,eigvec_=la.eig(n.T@m) 
# print('svd-overlap eigenvalues:',eigv,'; gensvd-overlap eigenvalues:',eigv_)
# let the derivative of the transfer function equals to one of the eigenvalues
phid = 1/eigv[0]
# then measure the dynamics of kappa under basis vectors M -- m
# give the initial network activity
x0 = np.reshape(np.array([-0.4,.25]),(2,1))
diagkappa_M = la.inv(m)@x0
# diagkappa_M = 0.6*geneigvec
diagkappa_m = la.inv(mlvec)@x0
tf,dt=20,0.001
nt = int(tf/dt)
tt = np.arange(nt)*dt
kappa_M,kappa_M_,kappa_m,kappa_m_=np.zeros((2,nt),dtype=complex),np.zeros((2,nt),dtype=complex),np.zeros((2,nt),dtype=complex),np.zeros((2,nt),dtype=complex)
kappa_M[:,0],kappa_m[:,0]=diagkappa_M[:,0],diagkappa_m[:,0]
kappa_m_[:,0],kappa_M_[:,0]=sigmavinv@Mcheck.T@kappa_M[:,0],-kappa_M[:,0]
for i in range(1,nt):
    dkappa_M=-kappa_M[:,i-1]+np.squeeze(phid*genover@np.reshape(kappa_M[:,i-1],(2,1)))
    dkappa_M_=-kappa_M_[:,i-1]+np.squeeze(phid*genover@np.reshape(kappa_M_[:,i-1],(2,1)))
    # print('delta kappa:',dkappa_M)
    dkappa_m=-kappa_m[:,i-1]+np.squeeze(phid*svdover@np.reshape(kappa_m[:,i-1],(2,1)))

    kappa_M[:,i]=dkappa_M*dt+kappa_M[:,i-1]
    kappa_M_[:,i]=dkappa_M_*dt+kappa_M_[:,i-1]
    kappa_m_[:,i]=sigmavinv@Mcheck.T@kappa_M[:,i]#
    kappa_m[:,i]=dkappa_m*dt+kappa_m[:,i-1]

# fig,ax = plt.subplots(1,2)
# # ax=ax.flatten()
# ax0=ax[0].plot(tt,kappa_m[0,:],'r')
# ax0=ax[0].plot(tt,kappa_m[1,:],'b')
# ax0=ax[0].plot(tt,kappa_m_[0,:],'r--')
# ax0=ax[0].plot(tt,kappa_m_[1,:],'b--')
# ax1=ax[1].plot(tt,kappa_M[0,:],'r')
# ax1=ax[1].plot(tt,kappa_M[1,:],'b')
# ax1=ax[1].plot(tt,kappa_M_[0,:],'r--')
# ax1=ax[1].plot(tt,kappa_M_[1,:],'b--')
kappa_stm,kappa_stM=kappa_m[:,-1],kappa_M[:,-1]
print('equilibrium state under M:',kappa_stM[0],kappa_stM[1])#,'; under m:',kappa_stm[0],kappa_stm[1])
# print('corresponding eigenvectors under M:',geneigvec[0,0],geneigvec[1,0],'; under m:',svdeigvec[0,0],svdeigvec[1,0])
# print('rescale factor rho:', kappa_m_[:,-1]/kappa_m[:,-1])



equilibrium state under M: (-0.037485944833751166+1.5535059116089616j) (-0.16250370735579073-0.25327751961455497j)


In [89]:
# We give different initial kappa0 and find the fixed point(line) under same condition with identical eigenvalues and overlap matrix
tf,dt=20,0.01
nt = int(tf/dt)
tt = np.arange(nt)*dt
kmax,dk=0.5,0.01
nstep=int(2*kmax/dk)
# generate phase plane 
kappaM1,kappaM2=np.linspace(-kmax,kmax,nstep),np.linspace(-kmax,kmax,nstep)
kappaM_phase=np.zeros((nstep,nstep,2,nt),dtype=complex)
for idxk1, k1 in enumerate(kappaM1):
    for idxk2, k2 in enumerate(kappaM2):
        diagkappa_M = np.array([k1,k2])
        kappaM_phase[idxk1,idxk2,:,0]=diagkappa_M[:]
        for i in range(1,nt):
            dkappa_M=-kappaM_phase[idxk1,idxk2,:,i-1]+np.squeeze(phid*genover@np.reshape(kappaM_phase[idxk1,idxk2,:,i-1],(2,1)))
            kappaM_phase[idxk1,idxk2,:,i]=dkappa_M*dt+kappaM_phase[idxk1,idxk2,:,i-1]
  

In [93]:
# find the critical/threshold value
t_value=np.linspace(-20,20,1000)
mu,sig=0.0,1.0
t_value +=mu
t_mid=0.5*t_value[1:]+0.5*t_value[:-1]
mudist=np.exp(-(t_value-mu)**2/2.0/sig**2)/np.sqrt(2*np.pi)/sig
mudist_mid=np.exp(-(t_mid-mu)**2/2.0/sig**2)/np.sqrt(2*np.pi)/sig
z_value = -5
diff_u=np.diff(mudist)
num_sum=np.sum(diff_u*(z_value/(z_value**2-t_mid**2)))
theo_sum=np.sum(-z_value/(z_value**2-t_mid**2)*((t_mid-mu)/sig**2)*mudist_mid*(t_value[1]-t_value[0]))
print('num sum:',num_sum,'; theo_sum:',theo_sum)

num sum: -1.3877787807814457e-17 ; theo_sum: 0.0


In [111]:
t_value=np.linspace(-2,2,100)
mudist=np.sqrt(4-t_value**2)/(2*np.pi)
# mudist/=np.sum(mudist)
mudist/=4/100.0
t_mid=0.5*t_value[1:]+0.5*t_value[:-1]
z_value = 2.0000000001
diff_u=np.diff(mudist)*500**2
num_sum=np.sum(diff_u*(z_value/(z_value**2-t_mid**2)))/z_value
print('num sum:',num_sum)

num sum: -4.5634806153876706e-08
