## 17/12/2020 Update
# Linking and Comparing Local Connect Stats with Low-rank Recurrent Network
* From Local Connect Stats cite[Sharpee]
* From Low-rank structure to EI 

In [1]:
from __future__ import print_function
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets
import numpy as np
import matplotlib.pylab as plt
import matplotlib
%matplotlib qt
from numpy import linalg as la
from scipy.optimize import fsolve
from scipy import linalg as scpla
import seaborn as sb
from mpl_toolkits.axes_grid1 import make_axes_locatable
from cmath import *
from mpl_toolkits.mplot3d import Axes3D
from scipy.optimize import fsolve,leastsq 
from math import tanh,cosh
import math
from sympy import *
extras_require = {'PLOT':['matplotlib>=1.1.1,<3.0']},

## Check the results in Sharpee's paper
* local stats, EE,EI,IE,II occupy their own properties, independently
* no pair correlation


In [178]:
Nt=np.array([2000,1000])
NE,NI=Nt[0],Nt[1]
at = Nt/N
N=np.sum(Nt)
aee,aei,aie,aii=4.5,-6.0,5.0,-2.5
JEEsub,JEIsub,JIEsub,JIIsub=aee*np.ones((NE,NE))/NE,aei*np.ones((NE,NI))/NI,aie*np.ones((NI,NE))/NE,aii*np.ones((NI,NI))/NI
J = np.zeros((NE+NI,NE+NI))

# determine gcd
Gmat=np.zeros((2,2))
Gmatorg=np.array([[0.8,1.2],[0.9,0.2]])
# Gmat/=np.sqrt(N)
for i in range(2):
    for j in range(2):
        Gmat[i,j]=Gmatorg[i,j]/np.sqrt(N)
# EE
gij=Gmat[0,0]*np.random.randn(NE,NE)
J[:NE,:NE]=gij.copy()
# EI
gij=Gmat[0,1]*np.random.randn(NE,NI)
J[:NE,NE:]=gij.copy()
# IE
gij=Gmat[1,0]*np.random.randn(NI,NE)
J[NE:,:NE]=gij.copy()
# II
gij=Gmat[1,1]*np.random.randn(NI,NI)
J[NE:,NE:]=gij.copy()

P = np.zeros((N,N))
P[:NE,:NE],P[:NE,NE:],P[NE:,:NE],P[NE:,NE:]=JEEsub.copy(),JEIsub.copy(),JIEsub.copy(),JIIsub.copy()
X = P.copy()+J.copy()

In [113]:
gavg=np.sqrt(np.sum(np.sum(Gmat**2)))/2.0
print('averaging g noise:',gavg*np.sqrt(N))

averaging g noise: 0.8558621384311844


In [105]:
aee,aei,aie,aii=4.5,-6.0,5.0,-2.5
Asmall=np.array([[aee,aei],[aie,aii]])
eigva,_=la.eig(Asmall)
_,sigva,_=la.svd(Asmall)
print('eigenvalue:',eigva,'singular value:',sigva,'eigG',np.sqrt(eigG[0]))

eigenvalue: [1.+4.21307489j 1.-4.21307489j] singular value: [9.12570385 2.05463604] eigG 0.8546614831429354


In [179]:
# all about calculate eigenvalues
eigvrand,eigvecrand=la.eig(J)
eigstruct,eigvecstruct=la.eig(P)
# summation
X = P.copy()+J.copy()
eigvx,eigvecx=la.eig(X)
# theoretical
M = np.zeros((2,2))
for i in range(2):
    for j in range(2):
        M[i,j]=(Gmat[i,j]*np.sqrt(N))**2*(Nt[j]/N)
eigG,eigvecG=la.eig(M)
# low rank small
Asmall=np.array([[aee,aei],[aie,aii]])
eigva,_=la.eig(Asmall)


In [180]:
ticks = np.linspace(-2.0,2.0,3)
lims= [-2.1,2.1]

fig,ax=plt.subplots(figsize=(6,6))
ax.plot(np.sqrt(eigG[0])*np.ones(100),np.linspace(-1.0,1.0,100))
ax.scatter(np.real(eigvrand),np.imag(eigvrand),s=5.0,c='blue',alpha=0.5)
ax.scatter(np.real(eigstruct[:4]),np.zeros(4),s=15.0,c='red',alpha=0.5)
# ax.set_xlim(lims)
# ax.set_ylim(lims)
# ax.set_xticks(ticks)
# ax.set_yticks(ticks)
ax.set_aspect('equal')
ax.grid()

## relate this to low rank (here rank-2)

In [109]:
lvecX,svX,rvecXh=la.svd(X)
rvecX=rvecXh.T
m=lvecX[:,:2].copy()
n=rvecX[:,:2].copy()
n[:,0]*=svX[0]
n[:,1]*=svX[1]

# n[:,1]=rvecX[:,2]*svX[2]
# m[:,1]=lvecX[:,2]

In [111]:
morg,norg=m,n
fig,ax=plt.subplots(4,4,figsize=(9,9))
for i in range(2):
    for j in range(2):
        ax[i][j].scatter(morg[:NE,i],morg[:NE,j],s=5.0,c='red',alpha=0.05)
        ax[i][j].scatter(morg[NE:,i],morg[NE:,j],s=5.0,c='blue',alpha=0.05)
for i in range(2):
    for j in range(2):
        ax[2+i][2+j].scatter(norg[:NE,i],norg[:NE,j],s=5.0,c='red',alpha=0.05)
        ax[2+i][2+j].scatter(norg[NE:,i],norg[NE:,j],s=5.0,c='blue',alpha=0.05)
        
for i in range(2):
    for j in range(2):
        ax[i][2+j].scatter(morg[:NE,i],norg[:NE,j],s=5.0,c='red',alpha=0.05)
        ax[i][2+j].scatter(morg[NE:,i],norg[NE:,j],s=5.0,c='blue',alpha=0.05)
for i in range(2):
    for j in range(2):
        ax[2+i][j].scatter(norg[:NE,i],morg[:NE,j],s=5.0,c='red',alpha=0.05)
        ax[2+i][j].scatter(norg[NE:,i],morg[NE:,j],s=5.0,c='blue',alpha=0.05)
for i in range(4):
    for j in range(4):
        # ax[i][j].set_xlim(lims)
        # ax[i][j].set_ylim(lims)
        # ax[i][j].set_xticks(ticks)
        # ax[i][j].set_yticks(ticks)
        ax[i][j].set_aspect('equal')
        ax[i][j].grid()

In [117]:
# test Dale's law
Nt=np.array([300,100])
NE,NI=Nt[0],Nt[1]
N=np.sum(Nt)
aee,aei,aie,aii=4.5,-6.0,5.0,-2.5
JEEsub,JEIsub,JIEsub,JIIsub=aee*np.ones((NE,NE))/NE,aei*np.ones((NE,NI))/np.sqrt(NE*NI),aie*np.ones((NI,NE))/np.sqrt(NE*NI),aii*np.ones((NI,NI))/NI
P = np.zeros((N,N))
P[:NE,:NE],P[:NE,NE:],P[NE:,:NE],P[NE:,NE:]=JEEsub.copy(),JEIsub.copy(),JIEsub.copy(),JIIsub.copy()
eigvP,_=la.eig(P)
_,sigvp,_=la.svd(P)
Asmall=np.array([[aee,aei],[aie,aii]])
eigva,_=la.eig(Asmall)
_,sigva,_=la.svd(Asmall)

print('eigenvalue:',eigvP[:2],eigva[:2])
print('singular value:',sigvp[:2],sigva[:2])

eigenvalue: [1.+4.21307489j 1.-4.21307489j] [1.+4.21307489j 1.-4.21307489j]
singular value: [9.12570385 2.05463604] [9.12570385 2.05463604]


In [184]:
# test Dale's law
Nt=np.array([100,1000])
NE,NI=Nt[0],Nt[1]
N=np.sum(Nt)
at=Nt/N
# determine gcd
Gmat=np.zeros((2,2))
Gmatorg=np.array([[0.8,1.2],[0.9,0.2]])
# Gmat/=np.sqrt(N)
for i in range(2):
    for j in range(2):
        Gmat[i,j]=Gmatorg[i,j]/np.sqrt(N)
# EE
J=np.zeros((N,N))

gij=np.zeros((NE,NE))
gij=Gmat[0,0]*np.random.randn(NE,NE)
J[:NE,:NE]=gij.copy()
# EI
gij=np.zeros((NE,NI))
gij=Gmat[0,1]*np.random.randn(NE,NI)
J[:NE,NE:]=gij.copy()
# IE
gij=np.zeros((NI,NE))
gij=Gmat[1,0]*np.random.randn(NI,NE)
J[NE:,:NE]=gij.copy()
# II
gij=np.zeros((NI,NI))
gij=Gmat[1,1]*np.random.randn(NI,NI)
J[NE:,NE:]=gij.copy()

gavg=0
for i in range(2):
    for j in range(2):
        gavg+=np.sqrt(Gmatorg[i,j]**2*at[i]*at[j])
M = np.zeros((2,2))
for i in range(2):
    for j in range(2):
        M[i,j]=(Gmatorg[i,j]**2)*at[j]

eigvj,_=la.eig(J)
eigvM,_=la.eig(M)
ticks = np.linspace(-2.0,2.0,3)
lims= [-2.1,2.1]

fig,ax=plt.subplots(figsize=(6,6))
ax.plot(np.sqrt(eigvM[0])*np.ones(100),np.linspace(-1.0,1.0,100))
ax.scatter(np.real(eigvj),np.imag(eigvj),s=5.0,c='blue',alpha=0.5)
print('average eigv:',gavg)


average eigv: 0.858253007850327


In [227]:
# testing distribution of J_{ij}
NE,NI=750,250
sigm,sign=0.5,1.2
mE,nE=sigm*np.random.randn(NE,1)/np.sqrt(NE),sign*np.random.randn(NE,1)/np.sqrt(NE)
JEE = mE@nE.T 
eigv,eigvec=la.eig(JEE)
fig,ax=plt.subplots(figsize=(6,6))
ax.scatter(np.real(eigvj),np.imag(eigvj),s=5.0,c='blue',alpha=0.5)

JEEoff=JEE.copy()
JEEdiag=np.zeros(NE)
for i in range(NE):
    JEEoff[i,i:NE-1]=JEEoff[i,i+1:]
    JEEdiag[i]=JEE[i,i]
fig,ax=plt.subplots(2,1,figsize=(6,6))
Joff=JEEoff[:,:NE-1]
Joff=np.reshape(Joff,(NE**2-NE,1))
n, bins, patches = ax[0].hist(Joff, 100, density=True, alpha=0.5)
n, bins, patches = ax[1].hist(JEEdiag, 100, density=True, alpha=0.5)
print(sigm*sign)



0.6


## What's the distribution of $J_{i,j}$ in $\tilde{\mathbf{X}}=\mathbf{X}+\mathbf{p}$

In [229]:
# testing distribution of J_{ij} in \tilde{X}
NE,NI=2000,250
sigm,sign,grandom=0.6,1.0,0.5
rho=0.0
zetax,zetay=np.random.randn(NE,1),np.random.randn(NE,1)
m = sigm*zetax/np.sqrt(NE)
n =sign*(rho*zetax+np.sqrt(1-rho**2)*zetay)/np.sqrt(NE)
P = m@n.T 
X = (grandom)*np.random.randn(NE,NE)/np.sqrt(NE)

Xtilde=X+P

eigv,eigvec=la.eig(Xtilde)
fig,ax=plt.subplots(figsize=(6,6))
ax.scatter(np.real(eigv),np.imag(eigv),s=5.0,c='blue',alpha=0.5)

JEEoff=Xtilde.copy()
JEEdiag=np.zeros(NE)
for i in range(NE):
    JEEoff[i,i:NE-1]=JEEoff[i,i+1:]
    JEEdiag[i]=Xtilde[i,i]
fig,ax=plt.subplots(2,1,figsize=(6,6))
Joff=JEEoff[:,:NE-1]
Joff=np.reshape(Joff,(NE**2-NE,1))
n, bins, patches = ax[0].hist(Joff, 100, density=True, alpha=0.5)
n, bins, patches = ax[1].hist(JEEdiag, 100, density=True, alpha=0.5)

## Generate Random Block Matrix, embedding low rank structur $\tilde{\mathbf{X}}_{\mathrm{type}}=\mathbf{X}_{\mathrm{type}}+\mathbf{P}_{\mathrm{type}}$

In [238]:
phiacttt=np.zeros((N,1))
phiacttt[:NE,0],phiacttt[NE:,0]=(rhoE*zetaxE+np.sqrt(1-rhoE**2)*zetayE)/np.sqrt(N),(rhoI*zetaxI+np.sqrt(1-rhoI**2)*zetayI)/np.sqrt(N)
eitatt=Xtilde@phiacttt
eitarand=X@phiacttt
coveitatt=eitatt@eitatt.T 
coveitarand=eitarand@eitarand.T 
deltaEt,deltaEr=coveitatt[:NE,:NE],coveitarand[:NE,:NE]
deltaIt,deltaIr=coveitatt[NE:,NE:],coveitarand[NE:,NE:]
print('std, Et:',np.std(deltaEt),'; random:',np.std(deltaEr))
print('std, It:',np.std(deltaIt),'; random:',np.std(deltaIr))

In [411]:
eigvx,_=la.eig(X)
eigvxt,_=la.eig(Xtilde)
fig,ax=plt.subplots(2,2,figsize=(9,9))
ax[0][0].scatter(np.real(eigvx),np.imag(eigvx),s=2.0,c='red',alpha=0.5)
ax[0][0].set_aspect('equal')
print(np.sqrt(xee**2*NE/N))
ax[1][0].scatter(np.real(eigvxt),np.imag(eigvxt),s=2.0,c='red',alpha=0.5)
ax[1][0].set_aspect('equal')
# HISTOGRAM
n, bins, patches = ax[0][1].hist(np.real(eigvx), 20, density=True, alpha=0.5)
ax[0][1].set_xlim([-4.0,4.0])
n, bins, patches = ax[1][1].hist(np.real(eigvxt), 20, density=True, alpha=0.5)
ax[0][1].set_xlim([-4.0,4.0])
# SUBTYPE
XEI,XTEI=X[:NE,NE:],Xtilde[:NE,NE:]
eigvEI,eigvec=la.eig(XEI)
eigvTEI,eigvec=la.eig(XTEI)
fig,ax=plt.subplots(1,2,figsize=(6,6))
ax[0].scatter(np.real(eigvEI),np.imag(eigvEI),s=5.0,c='blue',alpha=0.5)
ax[1].scatter(np.real(eigvTEI),np.imag(eigvTEI),s=5.0,c='blue',alpha=0.5)

XEE,XTEE=X[:NE,:NE],Xtilde[:NE,:NE]
eigvEE,eigvec=la.eig(XEE)
eigvTEE,eigvec=la.eig(XTEE)
fig,ax=plt.subplots(1,2,figsize=(6,6))
ax[0].scatter(np.real(eigvEE),np.imag(eigvEE),s=5.0,c='red',alpha=0.5)
ax[1].scatter(np.real(eigvTEE),np.imag(eigvTEE),s=5.0,c='red',alpha=0.5)

XIE,XTIE=X[NE:,:NE],Xtilde[NE:,:NE]
eigvIE,eigvec=la.eig(XIE)
eigvTIE,eigvec=la.eig(XTIE)
fig,ax=plt.subplots(1,2,figsize=(6,6))
ax[0].scatter(np.real(eigvIE),np.imag(eigvIE),s=5.0,c='blue',alpha=0.5)
ax[1].scatter(np.real(eigvTIE),np.imag(eigvTIE),s=5.0,c='blue',alpha=0.5)

XII,XTII=X[NE:,NE:],Xtilde[NE:,NE:]
eigvII,eigvec=la.eig(XII)
eigvTII,eigvec=la.eig(XTII)
fig,ax=plt.subplots(1,2,figsize=(6,6))
ax[0].scatter(np.real(eigvII),np.imag(eigvII),s=5.0,c='red',alpha=0.5)
ax[1].scatter(np.real(eigvTII),np.imag(eigvTII),s=5.0,c='red',alpha=0.5)


1.7677669529663689


# 24/12 Generate Figures and Some Questions

## Generate Matrix

In [971]:
Nt=np.array([1000,1000])
NE,NI=Nt[0],Nt[1]
N=NE+NI
at = Nt/N
N=np.sum(Nt)

# Block Gaussian Random Network
# xee,xei,xie,xii=2.0,0.0,0.0,1.0

xee,xei,xie,xii=2.0,1.5*2.0/2.5,1.0/1.5*2.5,1.0
X,P=np.random.randn(N,N),np.zeros((N,N))
X[:NE,:NE],X[NE:,NE:]=xee*X[:NE,:NE]/np.sqrt(NE),xii*X[NE:,NE:]/np.sqrt(NI)
X[:NE,NE:],X[NE:,:NE]=xei*X[:NE,NE:]/np.sqrt(NE),xie*X[NE:,:NE]/np.sqrt(NI)

# X[:NE,:NE],X[:NE,NE:]=xee*X[:NE,:NE]/np.sqrt(N),xei*X[:NE,NE:]/np.sqrt(N)
# X[NE:,:NE],X[NE:,NE:]=xie*X[NE:,:NE]/np.sqrt(N),xii*X[NE:,NE:]/np.sqrt(N)
# print('std indeed:',xee/np.sqrt(N),xei/np.sqrt(N),xie/np.sqrt(N),xii/np.sqrt(N))
eigvx,eigvecx=la.eig(X)
# theoretical M (grandom) matrix 
gmat = np.array([[xee**2,xei**2],[xie**2,xii**2]])
# first do not multiply at
gaverage=0
for i in range(2):
    for j in range(2):
        gaverage+=gmat[i,j]/2 # ntype=2
gaverage=np.sqrt(gaverage)
# for i in range(2):
#     gmat[:,i]*=at[i]
print(gmat)
eigvgm,eigvecgm=la.eig(gmat)
print('square root radius')
print(np.sqrt(eigvgm[:]),gaverage)
ugm,svgm,vhgm=la.svd(gmat)
ngm=vhgm.copy()
ngm=ngm.T 
ngm[:,0],ngm[:,1]=svgm[0]*ngm[:,0],svgm[1]*ngm[:,1]

# mean value 
# first use rank-1 structure
JE,JI=2.5,1.5
Am=np.zeros((N,N))
Am[:,:NE],Am[:,NE:]=JE/NE,-JI/NI
# ua,svam,vha=la.svd(Am)
# va=vha.T
# svam=svam[0]
ua,va=np.zeros((N,N)),np.zeros((N,N))
ua[:,0]=1.0/np.sqrt(N)
va[:NE,0]=JE/np.sqrt(NE)
va[NE:,0]=-JI/np.sqrt(NI)
va[:,0]/=-np.linalg.norm(va[:,0])
svam=np.sqrt(2*(JE**2+JI**2))
vha=va.T

[[4.         1.44      ]
 [2.77777778 1.        ]]
square root radius
[2.23606798e+00 1.49011612e-08] 2.146832291747282


In [972]:
# First Set of Figures
# figure, validate results in sharpee's paper
# ticks and labels
ticks = np.linspace(-2.0,2.0,5)
lims= [-2.1,2.1]
nbins=100
fig,ax=plt.subplots(1,2,figsize=(10,4.5))
# eigenvalue
ax[0].scatter(np.real(eigvx),np.imag(eigvx),s=2.0,c='blue',alpha=0.5)
# ax[0].set_xlim(lims)
# ax[0].set_ylim(lims)
# ax[0].set_xticks(ticks)
# ax[0].set_yticks(ticks)
ax[0].set_aspect('equal')

## put them together and try to figure out the the properties

In [973]:
Xtotal=X.copy()+Am.copy()
# singular decomposition blockage
XEEtotal,XEItotal,XIEtotal,XIItotal=Xtotal[:NE,:NE],Xtotal[:NE,NE:],Xtotal[NE:,:NE],Xtotal[NE:,NE:]
uxtEE,svxtEE,vhxtEE=la.svd(XEEtotal)
vxtEE=vhxtEE.T
uxtEI,svxtEI,vhxtEI=la.svd(XEItotal)
vxtEI=vhxtEI.T
uxtIE,svxtIE,vhxtIE=la.svd(XIEtotal)
vxtIE=vhxtIE.T
uxtII,svxtII,vhxtII=la.svd(XIItotal)
vxtII=vhxtII.T
uxt,svxt,vhxt=la.svd(Xtotal)
vxt=vhxt.T
ux,svx,vhx=la.svd(X)
vx=vhx.T
print(svxt[:5])
print(svx[:5])

# ## test EE and II separately
# iiduxt,iidvxt=np.zeros((2,1)),np.zeros((2,1))
# iiduxt[0,0],iiduxt[1,0]=np.mean(uxtEE[:,0]),np.mean(uxtII[:,0])
# iidvxt[0,0],iidvxt[1,0]=np.mean(vxtEE[:,0]),np.mean(vxtII[:,0])
# mua,mva = np.zeros((2,1)),np.zeros((2,1))
# mua[0,0],mua[1,0]=ua[0,0],ua[NE+1,0]
# mva[0,0],mva[1,0]=va[0,0],va[NE+1,0]
# # noise components E and I seperate 
# iidnu,iidnv=np.zeros((NE,2)),np.zeros((NE,2))
# # for E noise
# iidnu[:,0]=(uxtEE[:,0]-iiduxt[0,0])
# iidnv[:,0]=(vxtEE[:,0]-iidvxt[0,0])
# # for I noise
# iidnu[:,1]=(uxtII[:,0]-iiduxt[1,0])
# iidnv[:,1]=(vxtII[:,0]-iidvxt[1,0])



[5.46671122 4.64289958 4.62532079 4.60764099 4.59254261]
[4.64599267 4.62620241 4.60925445 4.59362846 4.58549003]


In [976]:
## test EE and II separately
iiduxt,iidvxt=np.zeros((2,1)),np.zeros((2,1))
iiduxt[0,0],iiduxt[1,0]=np.mean(uxtEE[:,0]),np.mean(uxtII[:,0])
iidvxt[0,0],iidvxt[1,0]=np.mean(vxtEE[:,0]),np.mean(vxtII[:,0])
mua,mva = np.zeros((2,1)),np.zeros((2,1))
mua[0,0],mua[1,0]=ua[0,0],ua[NE+1,0]
mva[0,0],mva[1,0]=va[0,0],va[NE+1,0]
# noise components E and I seperate 
iidnu,iidnv=np.zeros((NE,2)),np.zeros((NE,2))
# for E noise
iidnu[:,0]=(uxtEE[:,0]-iiduxt[0,0])
iidnv[:,0]=(vxtEE[:,0]-iidvxt[0,0])
# for I noise
iidnu[:,1]=(uxtII[:,0]-iiduxt[1,0])
iidnv[:,1]=(vxtII[:,0]-iidvxt[1,0])
print('mean value:')
print(iiduxt,iiduxt[0,0]/iiduxt[1,0])
print('mean mE for total')
print(np.sqrt(1-(xee/JE)**2)/np.sqrt(NE),np.sqrt(1-(xii/JI)**2)/np.sqrt(NE),(np.sqrt(1-(xee/JE)**2)/np.sqrt(1-(xii/JI)**2)))

print('mean value:')
print(iidvxt,iidvxt[0,0]/iidvxt[1,0])
print('mean mE for total')
print(np.sqrt(1-(xee/JE)**2)/np.sqrt(NE),np.sqrt(1-(xii/JI)**2)/np.sqrt(NE),(np.sqrt(1-(xee/JE)**2)/np.sqrt(1-(xii/JI)**2)))

## test EE and II separately
iiduxt,iidvxt=np.zeros((2,1)),np.zeros((2,1))
iiduxt[0,0],iiduxt[1,0]=np.mean(uxtEE[:,0]),np.mean(uxtEI[:,0])
iidvxt[0,0],iidvxt[1,0]=np.mean(vxtEE[:,0]),np.mean(vxtEI[:,0])
mua,mva = np.zeros((2,1)),np.zeros((2,1))
mua[0,0],mua[1,0]=ua[0,0],ua[NE+1,0]
mva[0,0],mva[1,0]=va[0,0],va[NE+1,0]
# noise components E and I seperate 
iidnu,iidnv=np.zeros((NE,2)),np.zeros((NE,2))
# for E noise
iidnu[:,0]=(uxtEE[:,0]-iiduxt[0,0])
iidnv[:,0]=(vxtEE[:,0]-iidvxt[0,0])
# for I noise
iidnu[:,1]=(uxtEI[:,0]-iiduxt[1,0])
iidnv[:,1]=(vxtEI[:,0]-iidvxt[1,0])
print('mean value:')
print(iiduxt,iiduxt[0,0]/iiduxt[1,0])
print('mean mE for total')
print(np.sqrt(1-(xee/JE)**2)/np.sqrt(NE),np.sqrt(1-(xei/JI)**2)/np.sqrt(NE),(np.sqrt(1-(xee/JE)**2)/np.sqrt(1-(xei/JI)**2)))

print('mean value:')
print(iidvxt,iidvxt[0,0]/iidvxt[1,0])
print('mean mE for total')
print(np.sqrt(1-(xee/JE)**2)/np.sqrt(NE),np.sqrt(1-(xei/JI)**2)/np.sqrt(NE),(np.sqrt(1-(xee/JE)**2)/np.sqrt(1-(xei/JI)**2)))


mean value:
[[0.01963267]
 [0.02403156]] 0.8169536055674103
mean mE for total
0.018973665961010272 0.023570226039551584 0.8049844718999241
mean value:
[[ 0.01945911]
 [-0.0238054 ]] -0.8174240798603162
mean mE for total
0.018973665961010272 0.023570226039551584 0.8049844718999241
mean value:
[[ 0.01963267]
 [-0.01882729]] -1.0427773535160296
mean mE for total
0.018973665961010272 0.01897366596101028 0.9999999999999997
mean value:
[[0.01945911]
 [0.02021236]] 0.9627331233736269
mean mE for total
0.018973665961010272 0.01897366596101028 0.9999999999999997


In [977]:
print('real mean mx:')
print(np.mean(uxt[:NE,0]))

real mean mx:
-0.019296275719686142


In [901]:
print('iid sv:')
print(svxtEE[0],svxtII[0],svxtEE[0]/svxtII[0])
print(xee**2/JE+JE,xii**2/JI+JI)
# change of the mean value
mutE=uaE[0,0]*np.sqrt(1-xee**2/JE**2)#svam**2)#JE**2/4)
mvtE=vaE[0,0]*np.sqrt(1-xee**2/JE**2)#svam**2)#JE**2/4)
print('rotate E')
print(mutE,iiduxt[0,0],iidvxt[0,0])

iid sv:
4.1226128929638355 2.1539224358357476 1.9140024842000463
4.1 2.1666666666666665
rotate E
-0.013416407864998536 -0.01887099018727983 -0.018314179939325853


In [902]:
# standard deviation 
stdnu,stdnv=np.zeros(2),np.zeros(2)
stdnu[0],stdnu[1]=np.std(iidnu[:,0])*np.sqrt(NE),np.std(iidnu[:,1])*np.sqrt(NE)
print('std')
print(stdnu)
print(xee/JE,xii/JI)


std
[0.80242491 0.67011423]
0.8 0.6666666666666666


In [881]:
print('ratio of noise:')
print(np.sqrt(1-(muxtt[0,0]/ua[0,0])**2)**2)
print(np.sqrt(1-(muxtt[1,0]/ua[NE,0])**2)**2)

stdute,stduti=xee/np.std(uxt[:NE,0])/np.sqrt(NE),xii/np.std(uxt[NE:,0])/np.sqrt(NI)
stdvte,stdvti=np.std(vxt[:NE,0])*np.sqrt(NE),np.std(vxt[NE:,0])*np.sqrt(NI)

print(ua[0,0],muxtt[:,0],)
print(stdute,stduti,stdvte,stdvti)

ratio of noise:
nan
0.1509100308578967
-0.02236067977499756 [0.02256579 0.02060449]
8.355670620322547 10.571689665028934 0.2575338205112959 0.10550853272752397


In [789]:
# singular value
n, bins, patches = ax[1].hist(svx, nbins, density=True, alpha=0.5)
# ax[1].set_xlim(lims)
# ax[1].set_xticks(ticks+5)
ax[1].set_aspect('auto')

## noise covariance and mean-total covariance

In [790]:
## calculate the overlap matrix 
# overlap pure 2*2 m and n only
overlapmn=noisem.T@noisen
print('overlap matrix for mn:')
print(overlapmn)

# overlap total 4
overlap4T=noisevec.T@noisevec
print('total overlap:')
print(overlap4T)
evovT,evecovT=la.eig(overlap4T)
print('lambda')
# print(evecovT)
print(evovT)

## mean-total projection
utilde,vtilde=np.zeros((NE,2)),np.zeros((NE,2))
uorg,vorg=np.zeros((NE,2)),np.zeros((NE,2))

utilde[:,0],utilde[:,1]=uxt[:NE,0],uxt[NE:,0]
vtilde[:,0],vtilde[:,1]=vxt[:NE,0],vxt[NE:,0]
uorg[:,0],uorg[:,1]=ua[:NE,0],ua[NE:,0]
vorg[:,0],vorg[:,1]=va[:NE,0],va[NE:,0]
mtilde,ntilde=utilde.copy(),vtilde.copy()#*svxt[0]
morg,norg=uorg.copy(),vorg.copy()#*svam
transm=mtilde/morg#mtilde@morg.T@la.inv(morg@morg.T)
transn=ntilde/norg#ntilde@norg.T@la.inv(norg@norg.T)
# print('transformation')
# print(transm)
# print(transn)
ovtom,ovton=mtilde.T@morg,ntilde.T@norg#*svxt[0]*svx[0]
print('projection')
print(ovtom)
print(ovton)

overlap matrix for mn:
[[ 0.00354657  0.00057148]
 [ 0.00360612 -0.0008201 ]]
total overlap:
[[ 0.05231565  0.0030755   0.00354657  0.00057148]
 [ 0.0030755   0.12209013  0.00360612 -0.0008201 ]
 [ 0.00354657  0.00360612  0.15943086 -0.00092745]
 [ 0.00057148 -0.0008201  -0.00092745  0.01868941]]
lambda
[0.15991886 0.12185592 0.0520855  0.01866576]
projection
[[0.43561726 0.43561726]
 [0.47226551 0.47226551]]
[[ 0.39998986 -0.49998733]
 [-0.40092601  0.50115751]]


In [791]:
print(eigvgm[0]/svam+svam)
# deterministic components
utt,vtt=muxtt*NE,mvxtt*NE
#sigmau and v;
sig2ue=np.sum(noiseu[:,0]**2)
sig2ui=np.sum(noiseu[:,1]**2)
sig2ve=np.sum(noisev[:,0]**2)
sig2vi=np.sum(noisev[:,1]**2)
crosscov=np.zeros((2,2))
crosscov[0,0]=utt[0,0]**2*sig2ve+vtt[0,0]**2*sig2ue 
crosscov[0,1]=utt[0,0]**2*sig2vi+vtt[1,0]**2*sig2ue 
crosscov[1,0]=utt[1,0]**2*sig2ve+vtt[0,0]**2*sig2ui 
crosscov[1,1]=utt[1,0]**2*sig2vi+vtt[1,0]**2*sig2ui
print('covcross:',crosscov/NE) 
print('gmat:',gmat)
print('sigma noise:')
print(np.sqrt(sig2ue),np.sqrt(sig2ui))
print(np.sqrt(sig2ve),np.sqrt(sig2vi))
print('ratio')
print(np.sqrt(sig2ue)/np.sqrt(sig2ui))
print(np.sqrt(sig2ve)/np.sqrt(sig2vi))


3.04869190888884
covcross: [[0.08195629 0.02864194]
 [0.12117164 0.05862576]]
gmat: [[0.5   0.25 ]
 [1.25  0.125]]
sigma noise:
0.2287261451293771 0.3494139743484558
0.39928793601851537 0.13670923338041086
ratio
0.6545993060405713
2.9207093489248517


## Figure out parameters

In [697]:
y = 2.0*np.random.randn(1,1000)
yn = np.repeat(y,1000,axis=0)
x = 3.0*np.random.randn(1000,1)
xn = np.repeat(x,1000,axis=1)
jn=xn+yn
fig,ax=plt.subplots(figsize=(9,9))
# HISTOGRAM
n, bins, patches = ax.hist(np.reshape(jn,(1000*1000,1)), 100, density=True, alpha=0.5)
print(np.std(np.reshape(jn,(1000*1000,1))))
np.sqrt(2**2+3**2)

3.605426622632382


3.605551275463989

In [393]:
vector_1= np.squeeze(muxtt)
vector_2 = np.squeeze(mua)
angleu=calculate_angle(vector_1,vector_2)
vector_1= np.squeeze(mvxtt)
vector_2 = np.squeeze(mva)
anglev=calculate_angle(vector_1,vector_2)
print('angle u and v:',angleu,anglev)



angle u and v: 3.1188974719299405 3.139528066295619
angle u and v: 1.4288992721907374 1.4041395032366502


In [762]:
def calculate_angle(vector_1,vector_2):
    unit_vector_1 = vector_1 /np.linalg.norm(vector_1)
    unit_vector_2 = vector_2 /np.linalg.norm(vector_2)
    dot_product = np.dot(unit_vector_1, unit_vector_2)
    angle = np.arccos(dot_product)
    return angle

# back up code

In [879]:
Xtotal=X.copy()+Am.copy()
# singular decomposition
uxt,svxt,vhxt=la.svd(Xtotal)
vxt=vhxt.T
ux,svx,vhx=la.svd(X)
vx=vhx.T
print(svxt[:5])
print(svx[:5])


## dissect noise and mean components
## mean for total and original
muxtt,mvxtt=np.zeros((2,1)),np.zeros((2,1))
muxtt[0,0],muxtt[1,0]=np.mean(uxt[:NE,0]),np.mean(uxt[NE:,0])
mvxtt[0,0],mvxtt[1,0]=np.mean(vxt[:NE,0]),np.mean(vxt[NE:,0])
mua,mva = np.zeros((2,1)),np.zeros((2,1))
mua[0,0],mua[1,0]=ua[0,0],ua[NE+1,0]
mva[0,0],mva[1,0]=va[0,0],va[NE+1,0]
# noise components E and I seperate 
noiseu,noisev=np.zeros((NE,2)),np.zeros((NE,2))
# for E noise
noiseu[:,0]=(uxt[:NE,0]-muxtt[0,0])
noisev[:,0]=(vxt[:NE,0]-mvxtt[0,0])
# for I noise
noiseu[:,1]=(uxt[NE:,0]-muxtt[1,0])
noisev[:,1]=(vxt[NE:,0]-mvxtt[1,0])
noisem,noisen=noiseu.copy(),noisev.copy()#*svxt[0]

# noise components 4*4
noisevec = np.zeros((NE,4))
noisevec[:,:2]=noisem.copy()
noisevec[:,2:]=noisen.copy()


[6.44943161 4.00928745 3.98429257 3.96936678 3.94801228]
[4.00973264 3.98515474 3.97197553 3.94868445 3.92199661]


In [800]:
mleft=5.0*np.random.randn(NE,1)/np.sqrt(NE)
nright=4.0*np.random.randn(NE,1)/np.sqrt(NE)
Cnright = 3*np.ones((NE,1))
Cmleft = 1*np.ones((NE,1))
randomm=mleft@Cnright.T+Cmleft@nright.T 
lrand=np.reshape(randomm,(NE**2,1))
theostd = (5*3)**2/NE+(4*1)**2/NE
theostd = np.sqrt(theostd)
print('stdnum:',np.std(lrand),theostd)

stdnum: 0.4973373839263357 0.4909175083453431


In [ ]:
# # subject to
# sigmE,signI,sigmI,signE=2.0,3.0,1.0,4.0
# rhoE=xee/sigmE/signE*1.5
# rhoI=xii/sigmI/signI*1.5
# m,n=np.zeros((N,1)),np.zeros((N,1))
# zetaxE,zetayE,zetaxI,zetayI=np.random.randn(NE),np.random.randn(NE),np.random.randn(NI),np.random.randn(NI)
# m[:NE,0]=sigmE*zetaxE/np.sqrt(N)
# n[:NE,0]=signE*(rhoE*zetaxE+np.sqrt(1-rhoE**2)*zetayE)/np.sqrt(N)
# m[NE:,0]=sigmI*zetaxI/np.sqrt(N)
# n[NE:,0]=signI*(rhoI*zetaxI+np.sqrt(1-rhoI**2)*zetayI)/np.sqrt(N)
# P=m@n.T 
# Xtilde=X.copy()+P.copy()

In [284]:
stdme=np.std(lxvec[:NE,0])
stdmi=np.std(lxvec[NE:,0])
stdne=np.std(svx[0]*rxvec[:NE,0])
stdni=np.std(svx[0]*rxvec[NE:,0])
rm1=np.array([stdme,stdmi])
rm1=np.reshape(rm1,(2,1))
rn1=np.array([stdne,stdni])
rn1=np.reshape(rn1,(2,1))
stdme=np.std(lxvec[:NE,1])
stdmi=np.std(lxvec[NE:,1])
stdne=np.std(svx[1]*rxvec[:NE,1])
stdni=np.std(svx[1]*rxvec[NE:,1])
rm2=np.array([stdme,stdmi])
rm2=np.reshape(rm2,(2,1))
rn2=np.array([stdne,stdni])
rn2=np.reshape(rn2,(2,1))
gstdest=rm1@rn1.T +rm2@rn2.T 
print('cal g:',gstdest)
print('org g:',xee**2/N,xei**2/N,xie**2/N,xii**2/N)

cal g: [[0.00089115 0.00017327]
 [0.00276879 0.00053832]]
org g: 0.000625 0.0009 0.0025 0.000225


In [269]:
lxvec,svx,rxvech=la.svd(P)
rxvec=rxvech.T 
fig,ax=plt.subplots(2,2,figsize=(9,9))
nbins=30
n, bins, patches = ax[0][0].hist(lxvec[:NE,0], nbins, density=True, alpha=0.5)
n, bins, patches = ax[1][0].hist(lxvec[NE:,0], nbins, density=True, alpha=0.5)
n, bins, patches = ax[0][1].hist(rxvec[:NE,0], nbins, density=True, alpha=0.5)
n, bins, patches = ax[1][1].hist(rxvec[NE:,0], nbins, density=True, alpha=0.5)
